name: client_app
description: "Client App for Fatora System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Flutter Icons
  cupertino_icons: ^1.0.8

  # App dependencies (from old project)
  supabase_flutter: ^2.10.3
  crypto: ^3.0.3
  geolocator: ^14.0.2
  image_picker: ^1.0.7

  # For deep linking (choose one)
  uni_links2: ^0.6.0   # يفضل هذا لأنه الأحدث والأقل مشاكل

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # uncomment this if you have assets folder
  # assets:
  #   - assets/
